import type { Metadata } from "next";
import { Darker_Grotesque } from 'next/font/google'
import "./globals.css";

const darkerGrotesqueFont = Darker_Grotesque({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesqueFont.className} antialiased`}
      >
        <div>Thanos is here!</div>
        {children}
      </body>
    </html>
  );
}
